{% set name = "fenics-ffcx-ufcx" %}
{% set version = "0.9.0.dev" %}

# pins are usually updated on minor bumps:
# basix is currently co-versioned with ffcx
{% set major_minor = version.rsplit(".", 1)[0] %}
{% set ufl_version = "2024.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/fenics/ffcx/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: 8a854782dbd119ec1c23c4522a2134d5281e7f1bd2f37d64489f75da055282e3
  url: https://github.com/fenics/ffcx/archive/f6be44b9b9ba65312600febb22d10e6acb951806.tar.gz

build:
  number: 0

outputs:
  - name: fenics-ufcx
    script: build-ufcx.sh  # [not win]
    script: build-ufcx.bat  # [win]
    build:
      noarch: generic
      ignore_run_exports:
        # we don't use the compiler, but cmake still needs it
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
    requirements:
      build:
        - cmake
        - make  # [not win]
        - {{ compiler("c") }}
        - {{ stdlib("c") }}
      run:
        - __unix  # [not win]
        - __win  # [win]
    test:
      script: test-ufcx.sh  # [not win]
      script: test-ufcx.bat  # [win]
      files:
        - test-ufcx
      requires:
        - pkg-config
        - cmake
        - make
        - {{ compiler("cxx") }}
      commands:
        - test -f ${PREFIX}/include/ufcx.h  # [not win]
        - if not exist %LIBRARY_PREFIX%\include\ufcx.h  (exit 1)  # [win]
        - pkg-config --cflags ufcx
  - name: fenics-ffcx
    script: build-ffcx-py.sh  # [not win]
    script: build-ffcx-py.bat  # [win]
    build:
      noarch: python
    requirements:
      host:
        - python >=3.9
        - pip
        - setuptools >=62
        - wheel
      run:
        - python >=3.9
        - setuptools
        - numpy >=1.21
        - cffi
        - fenics-basix {{ major_minor }}.*
        - fenics-ufl {{ ufl_version }}.*
    test:
      source_files:
        - test
      requires:
        - pip
        - pytest >=6
        - {{ compiler("c") }}
        - {{ compiler("cxx") }}
      imports:
        - ffcx
      commands:
        - pytest -v test/test_jit_expression.py

about:
  home: https://fenicsproject.org
  summary: The FEniCSx Form Compiler
  description: |
    FFCx is a new version of the FEniCS Form Compiler.
    It is being actively developed and is compatible with DOLFINx.

    FFCx is a compiler for finite element variational forms.
    From a high-level description of the form in the Unified Form Language (UFL),
    it generates efficient low-level C code that can be used to assemble the corresponding discrete operator (tensor).
    In particular, a bilinear form may be assembled into a matrix and a linear form may be assembled into a vector.
    FFCx may be used either from the command line (by invoking the ffcx command) or as a Python module (import ffcx).
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: COPYING.LESSER
  doc_url: https://docs.fenicsproject.org/ffcx/v{{ version }}/
  dev_url: https://github.com/fenics/ffcx

extra:
  feedstock-name: fenics-ffcx
  recipe-maintainers:
    - minrk
